In [1]:
import tensorflow as tf
import numpy as np

In [2]:
fashion_mnist = tf.keras.datasets.fashion_mnist
(train_images, train_labels), (test_images, test_labels) = fashion_mnist.load_data()
train_images = tf.reshape(train_images, (train_images.shape[0],train_images.shape[1]*train_images.shape[2]))
test_images = tf.reshape(test_images, (test_images.shape[0],test_images.shape[1]*test_images.shape[2]))

In [109]:
condition = tf.less(train_images/255, 0.5)
train_images_b = tf.where(condition, 0.0, 1.0)
condition = tf.less(test_images/255, 0.5)
test_images_b = tf.where(condition, 0.0, 1.0)
train_images_b[0]

<tf.Tensor: shape=(784,), dtype=float32, numpy=
array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 0.,
       1., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1

In [117]:
index = np.random.randint(0, np.shape(train_images_b)[0], 2)
train_images_np = train_images_b.numpy()
train_images_np[index]

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [114]:
h[[1,3]],h

(array([0.67278709, 0.2893842 ]),
 array([0.1717065 , 0.67278709, 0.22078284, 0.2893842 , 0.63099499,
        0.66279008, 0.38804535, 0.24936905, 0.20700851, 0.53280702]))

In [41]:
nv = 784  # number of the visible unit
nh = 10  # number of the hidden unit
lr = 0.001  # learning rate
Maxiter = 1e4  # max loop time
batch_size = 128 

In [59]:
w = tf.Variable(tf.random.normal((nh, nv), stddev=0.01))
b = tf.Variable(tf.random.normal((nv,), stddev=0.01))
c = tf.Variable(tf.random.normal((nh,), stddev=0.01))

In [42]:
index = np.random.randint(0, np.shape(train_images_b)[0], batch_size)

In [43]:
index

array([ 7419, 48769, 31692, 34962, 38462, 34943,  5240,  6074, 37939,
       44755, 55644, 29162, 24028, 35527,  7398,  3730, 24233, 48044,
       39228,  2803, 27141, 41088, 15124, 48382,  6309, 34200, 49092,
        2710, 34430, 27027, 52177, 31935, 19987,  2955, 28541, 49944,
        6715, 23319, 49686, 41131, 38422, 20218, 27087, 38272, 20663,
        5120, 58250,  7670, 15764, 52426,  3310, 55231, 52293, 43522,
       11667, 44333, 41242, 25691,  2494, 15502, 24644, 28398, 10989,
       52479, 10583, 32037,  6073,  5109, 47590, 56739, 34278, 42934,
       13808, 32138, 49751,   993, 54620, 40976, 52619, 30996, 19929,
       48943, 33458,  2073, 49018, 23749, 22596, 27809, 47512, 39580,
       40110, 37196, 38573, 53594, 43387,  5411, 56689, 32396, 10540,
       50712, 12926, 17883, 13286, 34531, 41643, 59713, 26711, 42168,
       28155, 50453, 38905, 20100, 15051,  8525, 19277,  5246, 24678,
       25576, 32960,  7714,  1072, 58259, 41157, 20551, 30625,  5154,
       19958, 55388]

In [45]:
 h = np.zeros(nh)
 h

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [78]:
w.shape, train_images_b[0].shape
tf.reshape(tf.matmul(w,tf.reshape(train_images_b[0],(-1,1))),(-1,))+c

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([-0.05975975, -0.3156459 , -0.07718697,  0.29551706,  0.21746188,
        0.12829226,  0.25086302, -0.02190565, -0.12314035, -0.19781922],
      dtype=float32)>

In [57]:
tf.sigmoid([1.0,2.0])

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([0.7310586, 0.880797 ], dtype=float32)>

In [118]:

tmp = np.random.random_sample(10)
h = phv>=tmp
h=h*1.0
h

array([0., 0., 0., 1., 0., 1., 1., 0., 0., 1.])

In [80]:
phv=np.random.random_sample(10)
size = phv.shape[0]
tmp = np.random.random_sample(size)
h = phv>tmp
h.astype(np.float)

array([0., 0., 1., 1., 0., 1., 0., 1., 0., 0.])

In [92]:
#hidden_layer = [[]]
hidden_layer = np.append(hidden_layer, h)
hidden_layer.reshape(-1,size)

array([[0., 0., 1., 1., 0., 1., 0., 1., 0., 0.],
       [0., 0., 1., 1., 0., 1., 0., 1., 0., 0.],
       [0., 0., 1., 1., 0., 1., 0., 1., 0., 0.],
       [0., 0., 1., 1., 0., 1., 0., 1., 0., 0.],
       [0., 0., 1., 1., 0., 1., 0., 1., 0., 0.]])

In [94]:
np.outer([1,2],[2,4])

array([[2, 4],
       [4, 8]])

In [97]:
h = np.random.random_sample(10)
h

array([0.1717065 , 0.67278709, 0.22078284, 0.2893842 , 0.63099499,
       0.66279008, 0.38804535, 0.24936905, 0.20700851, 0.53280702])

In [98]:
np.where(h>=np.max(h),1,0)

array([0, 1, 0, 0, 0, 0, 0, 0, 0, 0])

In [100]:
np.reshape(h,(2,-1))

array([[0.1717065 , 0.67278709, 0.22078284, 0.2893842 , 0.63099499],
       [0.66279008, 0.38804535, 0.24936905, 0.20700851, 0.53280702]])

In [101]:
h

array([0.1717065 , 0.67278709, 0.22078284, 0.2893842 , 0.63099499,
       0.66279008, 0.38804535, 0.24936905, 0.20700851, 0.53280702])

In [103]:
tf.one_hot([1,2],10)

<tf.Tensor: shape=(2, 10), dtype=float32, numpy=
array([[0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [106]:
y2 = tf.one_hot(test_labels[0],10)
y2

<tf.Tensor: shape=(10,), dtype=float32, numpy=array([0., 0., 0., 0., 0., 0., 0., 0., 0., 1.], dtype=float32)>

In [107]:
y1 =  ycls = np.where(h>=np.max(h),1,0)
y1

array([0, 1, 0, 0, 0, 0, 0, 0, 0, 0])

In [108]:
np.multiply(y1,y2)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [129]:
 print("The final accuracy is {:0.53f}".format(0.3))

The final accuracy is 0.29999999999999998889776975374843459576368331909179688


In [130]:
np.random.random_sample(5)

array([0.658498  , 0.39604384, 0.03323695, 0.60772817, 0.58001163])

In [131]:
phv = np.random.random_sample(10)
tmp = np.random.random_sample(10)
h = phv>=tmp
h=np.array(h).astype(np.float32)
phv,tmp,h

(array([0.4719603 , 0.12057056, 0.63633793, 0.71045466, 0.41863208,
        0.33875358, 0.19150683, 0.68547281, 0.51787147, 0.7974279 ]),
 array([0.83774361, 0.59541307, 0.61464253, 0.53240703, 0.4304117 ,
        0.09978484, 0.80510581, 0.59313733, 0.40854649, 0.9066026 ]),
 array([0., 0., 1., 1., 0., 1., 0., 1., 1., 0.], dtype=float32))

In [133]:
ycls = np.where(phv>=np.max(phv),1.0,0.0)
ycls

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 1.])